name: Prebuild Bevy Base Image

on:
  workflow_dispatch:  # Allows manual triggering of prebuild
    inputs:
      force_prebuild:
        description: "Force prebuild of Bevy base image"
        required: false
        default: "false"

jobs:
  prebuild:
    name: 🏗 Prebuild Rust + Bevy Image
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Needed to push to GHCR

    steps:
      - name: 🔄 Checkout repository
        uses: actions/checkout@v4

      - name: 🔑 Log in to GitHub Container Registry (GHCR)
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 🛠 Build & Push Prebuilt Docker Image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.actor }}/bevy-wasm-base"
          IMAGE_NAME_LOWER=$(echo $IMAGE_NAME | tr '[:upper:]' '[:lower:]')

          docker build -t $IMAGE_NAME_LOWER -f docker/Dockerfile.prebuild .
          docker push $IMAGE_NAME_LOWER
